### ISSUE TITLE
Echéancier

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-habilitation#17]

**Comment by killiankopp** [comment]
todo

**Comment by TigrouForMatic** [comment]
- [ ] Récupérer les infos sur les types habilitations

/v2/controle/habilitation/type

liste d'ids

- [ ] Récupérer les infos sur les habilitations

/v2/controle/habilitation

liste de personnel_id
ou
liste de habilitation_type_id

- [ ] ajouter des restricttions de période faclutatives

/v2/contrat

- [ ] à créer pour récupérer des contrats à partir d'une liste d'ids

/v2/personnel

- [ ] elle existe à tester !

/v2/controle

- [ ] à créer pour récupérer la liste des kn en fonction de critères (habilitation_type_id + personnel_id)

Filtres

- [ ] habilitation : select multiple

- [ ] opérateur : select multiple + gérer sous contrat ou hors contrats peut-être dans 2 liste distinctes

- [ ] choix du mode d'affichage : par habilitation ou par opérateur

**Comment by killiankopp** [comment]
@heligonSeb peux-tu développer /v2/controle
- habilitation_type_id : id ou liste d'ids (12 ou 3, 4, 9) table mkg_characteristic
- personnel_id : id ou liste d'ids (12 ou 3, 4, 9) table mkg_structure__personnel
- habilitation_id : id ou liste d'ids (12 ou 3, 4, 9) table mkg_characteristic__personnel
- dd (facultatif)
- df (facultatif)

## todo
- développer la route
- documenter la route
- tester le résultat pour Mari et Jules

## Retours
Pour Jules : liste des controles à afficher dans sa timeline
Le résultat du KN (S, A, M ou I) sera placé dans la case de la semaine correspondant à la ligne affichée qui sera une habilitation (CharacteristicPersonnel). Il faut pouvoir en un appel récupérer toutes les données, on précise une période à l'aide d'une date ou d'une date partielle (semaine) + des types d'habilitations ou du personnel ou les deux et tu renvoies la liste des KN concernés

Pour Mari : résultat des contrôles à afficher entre son habilitation et la veille de celle-ci
Une chaîne de lettre de contrôle M M S S A I M S. Il faut pouvoir faire un appel pour récupérer toutes les données : on précise une ou plusieurs habilitation (CharacteristicPersonnel) et tu renvoies les KN concernés

Détail
- habilitation_type_id
- personnel_id
- habilitation_id
- result (le resultat SAMI par ex)
- datetime
et rien de plus dans les données... il faut les renommer, nettoyer et filtrer ! tu me dis si tu veux des explications mais je ne veux pas de corbeille, sess_login_id, dc, dm ... et j'en passe

**Comment by heligonSeb** [comment]
changer personnel_id par operateur_id->cible_structure__personnel_id et controleur_id->enqueteur_structure__personnel_id

**Comment by TigrouForMatic** [comment]
Cette issue est fermée sur l'application ouverte, vous pouvez retrouver celle qui l'a remplace sur l'aplpication QSE-habilitation sur l'issue : Echeancier #33
